### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mporracindie** [opendistro-for-elasticsearch/job-scheduler#19]
Hi, it would be great to have a little bit more documentation on this plugin or even add it to the official OpenDistro docs.

**Comment by alolita** [comment]
Hi @mporracindie Agree! There is more documentation on the JobScheduler in the works. Are there specific areas you would like to see more details on?

**Comment by 0m1xa** [comment]
It's almost December already. 
Last comment was added in June.
Where is the documentation? оО

**Comment by praveensameneni** [comment]
@mporracindie , Here's the documentation link for Alerting, feel free to comment on it
https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/
