### ISSUE TITLE
Support schedule hint from job runner

### ISSUE THREAD

**Issue by zengyan-amazon** [opendistro-for-elasticsearch/job-scheduler#2]
One feature request we got is to allow more dynamic job scheduling. The idea is to allow job runner to return a hint to scheduler, indicate the when to execute the job runner next time. Then scheduler can evaluate the hint time and override the scheduled next execution if possible.

**Comment by dbbaughe** [comment]
This repo is deprecated, closing in favor of https://github.com/opensearch-project/job-scheduler/issues/91
