### ISSUE TITLE
Standardize version number

### ISSUE THREAD

**Issue by aetter** [opendistro-for-elasticsearch/job-scheduler#25]
Job Scheduler should use the same four-digit version numbers as the other plugins. Currently it uses three.

```
$ curl -XGET --insecure https://localhost:9200/_cat/plugins -u admin:admin
a44d0821e28e opendistro-job-scheduler        1.1.0
a44d0821e28e opendistro_alerting             1.1.0.0
a44d0821e28e opendistro_performance_analyzer 1.1.0.0
a44d0821e28e opendistro_security             1.1.0.0
a44d0821e28e opendistro_sql                  1.1.0.0
```

**Comment by chuanzgh** [comment]
+1
this odd-ball version numbering makes scripting... clunky and hacky.

**Comment by skkosuri-amzn** [comment]
Checked 1.8.0 and 1.9.0 releases, this is fixed.
curl -XGET --insecure https://localhost:9200/_cat/plugins -u admin:admin
<my-node> opendistro-job-scheduler        1.8.0.0
