### ISSUE TITLE
Add ability to disable job scheduling of specified extension plugin

### ISSUE THREAD

**Issue by zengyan-amazon** [opendistro-for-elasticsearch/job-scheduler#3]
JobScheduler plugin maybe extended by multiple extension plugins. Extension plugins may support the configuration to allow users to disable the plugin at runtime, which requires all scheduled jobs of that plugin to be descheduled.

Let extension plugin to disable all jobs by updating all job documents by setting ```enabled``` flag to ```false``` is an option, but it is not ideal, as the ```enabled``` field is meant for extension plugins to control at job level to support their use cases.

Thus we may want to implement a new mechanism for extension plugins to disable all their jobs at one shot.

**Comment by zengyan-amazon** [comment]
One potential option is to add a extension plugin blacklist setting for JobScheduler. If extension plugin wants to disable all their jobs, they can add itself to the blacklist. JobScheduler listens to this setting change and disable the jobs accordingly

**Comment by sixdouglas** [comment]
Hi,
Do you think I can involve for this improvement? If so, do you have more inputs/thoughts since the beginning of May?

**Comment by zengyan-amazon** [comment]
Hi @sixdouglas ,

Your involvement is welcomed. We didn't have a chance to finalized the approach we want to adopt since May due to limited bandwidth.

I believe the high level idea is allow extension plugin to update a setting to notify the JobScheduler to disable/re-enable its jobs. Then job scheduler can take care of the deschedule/schedule accordingly. However we are not sure whether is will be a cluster setting, or an index setting of extension plugins' job index, or some other type of setting.

Please let us know if you have any suggestions, and we would be happy to discuss any possibilities and move this forward.

Thanks

**Comment by dbbaughe** [comment]
This repo is deprecated, closing in favor of https://github.com/opensearch-project/job-scheduler/issues/92
