### ISSUE TITLE
Ability to schedule jobs at predefined time.

### ISSUE THREAD

**Issue by agllno** [opendistro-for-elasticsearch/job-scheduler#43]
We have use case where we need to have jobs run at predefined time as these are Aggregation/Rollup jobs that need to be executed for say at the end of every hour, every 1 day and so on.

For now, it looks like when Elasticsearch is restarted, Jobs are scheduled based on time Elasticsearch is restarted thus causing delays and sometimes even some jobs also missed depending on time Elastic search is restarted. Instead of arbitrary scheduling can we have option where user can set start Time for Job or atleast have Job after restart of Elasticsearch run based on last run time.

**Comment by zengyan-amazon** [comment]
@agllno according to our implementation, the jobs should be scheduled at predefined time for both CronSchedule and Interval Schedule. 

[JobScheduler](https://github.com/opendistro-for-elasticsearch/job-scheduler/blob/master/src/main/java/com/amazon/opendistroforelasticsearch/jobscheduler/scheduler/JobScheduler.java#L143) calls the `getNextExecutionTime` method of the schedule implementation to schedule the next execution of the job. For [CronSchedule](https://github.com/opendistro-for-elasticsearch/job-scheduler/blob/master/spi/src/main/java/com/amazon/opendistroforelasticsearch/jobscheduler/spi/schedule/CronSchedule.java#L80) it calculate the execution time based on the cron string, and for [InternalSchedule](https://github.com/opendistro-for-elasticsearch/job-scheduler/blob/master/spi/src/main/java/com/amazon/opendistroforelasticsearch/jobscheduler/spi/schedule/IntervalSchedule.java#L89) it calculate the next execution time based on the interval and job `startTime`, as long as the start time in your config index doesn't change, the schedule should be deterministic .

Please let me know if I misread your question.

**Comment by agllno** [comment]
@zengyan-amazon Thanks for explanation will close this issue
