### ISSUE TITLE
Issue regarding lock service while job deletion

### ISSUE THREAD

**Issue by agllno** [opendistro-for-elasticsearch/job-scheduler#54]
When we delete a job, how lock is handled. If we delete the job without releasing or deleting it from lock table we might leave an entry in lock index right?

Also when we lock the job will it lock and write threads until the time mentioned or lock is released?

**Comment by agllno** [comment]
@zengyan-amazon Can you please update on this?

**Comment by zengyan-amazon** [comment]
@agllno  sorry for the delayed response.

Technically, if the extension plugin of JobScheduler handles lock properly, there won't be a problem.  Regarding to your questions:


*When we delete a job, how lock is handled. If we delete the job without releasing or deleting it from lock table we might leave an entry in lock index right?*

yes, when disable/deleting a job from job index, job scheduler won't do anything about lock. however, JobScheduler will not interrupt the job execution if the job is running when you deleting it. so your job runner can still execute to complete and release the lock safely. If the node crashes when the job is running, it will leave a lock in the lock index, your job runner can only acquire lock when the TTL expires

*Also when we lock the job will it lock and write threads until the time mentioned or lock is released?*

I don't quite get it when you say **"lock and write threads"** here, a lock is essentially a document in the lock index, you can specify a TTL when you acquire the lock. if the lock is left unreleased, another job execution have to wait till the TTL is expired, then they can acquire the  lock again.

Hope this answers your question

**Comment by zengyan-amazon** [comment]
by saying TTL, I mean the return value of `getLockDurationSeconds` in [ScheduledJobParameter](https://github.com/opendistro-for-elasticsearch/job-scheduler/blob/master/spi/src/main/java/com/amazon/opendistroforelasticsearch/jobscheduler/spi/ScheduledJobParameter.java#L55)
