### ISSUE TITLE
Job sweeper fails to remove deleted jobs

### ISSUE THREAD

**Issue by dbbaughe** [opendistro-for-elasticsearch/job-scheduler#65]
Found from this forum discussion in ISM: https://discuss.opendistrocommunity.dev/t/ism-attempting-to-interact-with-an-obsolete-index/3224

Job scheduler has an in-memory map that contains the scheduled jobs that are scheduled to run. When a job document is created, updated, or deleted this map is updated with the appropriate action. In this specific case the delete somehow failed which left a job that was still executing every 2 hours even though it didn't exist anymore. Ideally the sweeper would catch this and resolve the failure, but the sweeper has a bug where it doesn't remove jobs that were deleted.

For reference:

The sweeper is a [background process that sweeps the job indices](https://github.com/opendistro-for-elasticsearch/job-scheduler/blob/master/src/main/java/com/amazon/opendistroforelasticsearch/jobscheduler/sweeper/JobSweeper.java#L278) for job documents to schedule, re-schedule, and de-schedule documents. It does this on an interval defined by [the sweep period](https://github.com/opendistro-for-elasticsearch/job-scheduler/blob/master/src/main/java/com/amazon/opendistroforelasticsearch/jobscheduler/sweeper/JobSweeper.java#L127). Every execution it will [sweep all indices](https://github.com/opendistro-for-elasticsearch/job-scheduler/blob/master/src/main/java/com/amazon/opendistroforelasticsearch/jobscheduler/sweeper/JobSweeper.java#L310) that were registered by plugins extending job scheduler which in turn will [sweep the shards for each index](https://github.com/opendistro-for-elasticsearch/job-scheduler/blob/master/src/main/java/com/amazon/opendistroforelasticsearch/jobscheduler/sweeper/JobSweeper.java#L357). This sweepShard function is the one with the bug that is not handling job documents that were deleted from the index.

**Comment by ftianli-amzn** [comment]
Thanks @dbbaughe for the detailed and well-organized explanation. 
Through your description, I think the problem is caused here: when [de-scheduling fails](https://github.com/opendistro-for-elasticsearch/job-scheduler/blob/28f0449e98fa1fc1fee1061babe48b4e4c550da0/src/main/java/com/amazon/opendistroforelasticsearch/jobscheduler/scheduler/JobScheduler.java#L102), there is no backup to retry or anything else to deal with the failure .

**Comment by dbbaughe** [comment]
Closing in favor of: https://github.com/opensearch-project/job-scheduler/issues/96
